// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcgudslnkzkyvhmraxfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZ3Vkc2xua3preXZobXJheGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTQzNjUsImV4cCI6MjA2NDE3MDM2NX0.GmI4AA2YMUHV2LVLmZPH0wo4WH2G68hGTtDCDcMm7GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);